[build]
nixpacks.nodejs_version = "18"

[deploy]
startCommand = "npm start"
restartPolicyType = "ON_FAILURE"
healthcheckPath = "/health"
healthcheckTimeout = 100

[[services]]
name = "api"
type = "web"

[env]
PORT = "8080"
NODE_ENV = "production"
ALLOWED_ORIGINS = "https://ai-powered-job-match.netlify.app,https://ai-powered-job-match-platform.vercel.app"