[build]
nixpacks.nodejs_version = "18"

[deploy]
startCommand = "npm start"
restartPolicyType = "ON_FAILURE"
healthcheckPath = "/health"
healthcheckTimeout = 100

[[services]]
name = "api"
type = "web"

[env]
PORT = "8080"
NODE_ENV = "production"
ALLOWED_ORIGINS = "https://ai-powered-job-match.netlify.app,https://ai-powered-job-match-platform.vercel.app,https://ai-powered-job-match.vercel.app,http://localhost:3000"
DB = "mongodb+srv://sravya6202:pTbZirImmSFZWDYr@cluster0.pn97uc9.mongodb.net/project?retryWrites=true&w=majority"
JWTPRIVATEKEY = "<your-jwt-private-key>"
SALT = "10"
OPENAI_API_KEY = "<your-openai-api-key>"
CLIENT_URL = "https://ai-powered-job-match.vercel.app"
API_URL = "https://ai-powered-job-match-platform-0g7r.onrender.com"