services:
  - type: web
    name: ai-powered-job-match
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8080
      - key: DB
        sync: false
      - key: JWTPRIVATEKEY
        sync: false
      - key: SALT
        value: 10
      - key: OPENAI_API_KEY
        sync: false
      - key: CLIENT_URL
        value: https://ai-powered-job-match.vercel.app