name: Azure Backend Deployment

on:
  push:
    branches:
      - main
    paths:
      - 'server/**'
  workflow_dispatch:

env:
  NODE_VERSION: '20.x'
  APP_NAME: 'jobmatchplatform-server'

jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    name: Deploy Backend
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: './server/package-lock.json'

      - name: Install Backend Dependencies
        working-directory: ./server
        run: npm ci

      - name: Run Tests
        working-directory: ./server
        run: npm test
        env:
          NODE_ENV: test
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
          GITHUB_CLIENT_ID: ${{ secrets.GITHUB_CLIENT_ID }}
          GITHUB_CLIENT_SECRET: ${{ secrets.GITHUB_CLIENT_SECRET }}

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Backend to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.APP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ./server
        env:
          NODE_ENV: production
          DB: ${{ secrets.MONGODB_URI }}
          JWTPRIVATEKEY: ${{ secrets.JWT_PRIVATE_KEY }}
          SALT: ${{ secrets.SALT }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
          GITHUB_CLIENT_ID: ${{ secrets.GITHUB_CLIENT_ID }}
          GITHUB_CLIENT_SECRET: ${{ secrets.GITHUB_CLIENT_SECRET }}
          BASE_URL: "https://jobmatchplatform-server.azurewebsites.net"
          CLIENT_URL: "https://lemon-coast-01b0ad500.3.azurestaticapps.net"
          ALLOWED_ORIGINS: "https://lemon-coast-01b0ad500.3.azurestaticapps.net"
